# Generated by Django 2.2 on 2021-05-16 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_userquery'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedDomain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_at', models.DateTimeField(auto_now=True, null=True)),
                ('domain', models.CharField(blank=True, max_length=512, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('block_status', models.BooleanField(blank=True, default=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
