# Generated by Django 2.2 on 2021-05-20 12:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_blockeddomain'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerifyMobileOTP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_at', models.DateTimeField(auto_now=True, null=True)),
                ('otp', models.CharField(blank=True, max_length=10, null=True)),
                ('valid', models.BooleanField(default=True)),
                ('time_limit', models.PositiveIntegerField(default=5, null=True)),
                ('today_attempts', models.PositiveIntegerField(default=1, null=True)),
                ('total_attempts', models.PositiveIntegerField(default=0, null=True)),
                ('last_attempted_at', models.DateTimeField(blank=True, null=True)),
                ('otp_created_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
