# Generated by Django 2.2 on 2021-03-06 11:53

from django.db import migrations, models
import storages.backends.s3boto3


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(storage=storages.backends.s3boto3.S3Boto3Storage(bucket='punam-flutes-prods'), upload_to=''),
        ),
    ]
