# Generated by Django 2.2 on 2020-05-28 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_countrycurrency'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='countrycurrency',
            options={'verbose_name_plural': 'Country Currencies'},
        ),
        migrations.AddField(
            model_name='countrycurrency',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.CountryCurrency'),
        ),
    ]
