# Generated by Django 2.2 on 2021-03-13 12:57

from django.db import migrations, models
import storages.backends.s3boto3


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20210306_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(storage=storages.backends.s3boto3.S3Boto3Storage(bucket='punam-flutes-prods'), upload_to='productImage/%Y%m%d%M%S'),
        ),
    ]
