# Generated by Django 2.2 on 2021-03-16 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20210313_1257'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('title', 'search_tags')},
        ),
    ]
