# Generated by Django 2.2 on 2020-07-29 08:47

from django.db import migrations, models
import storages.backends.s3boto3


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20200529_0206'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_image_1', models.ImageField(storage=storages.backends.s3boto3.S3Boto3Storage, upload_to='')),
                ('product_image_2', models.ImageField(blank=True, null=True, storage=storages.backends.s3boto3.S3Boto3Storage, upload_to='')),
                ('product_image_3', models.ImageField(blank=True, null=True, storage=storages.backends.s3boto3.S3Boto3Storage, upload_to='')),
                ('product_image_4', models.ImageField(blank=True, null=True, storage=storages.backends.s3boto3.S3Boto3Storage, upload_to='')),
                ('image_size', models.BigIntegerField(default=0.0)),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
