# Generated by Django 2.2 on 2020-07-29 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='product.ProductImage'),
        ),
    ]
