# Generated by Django 2.2 on 2021-04-16 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_product_publish'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('publish', 'title', 'search_tags')},
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_at', models.DateTimeField(auto_now=True, null=True)),
                ('type', models.CharField(blank=True, choices=[['limited', 'limited'], ['unlimited', 'unlimited']], max_length=100, null=True)),
                ('available', models.PositiveIntegerField(blank=True, null=True, default=0)),
                ('sold', models.PositiveIntegerField(blank=True, null=True, default=0)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='product.Product')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='countrycurrency',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product'),
        ),
    ]
