# Generated by Django 2.2 on 2020-07-29 11:04

from django.db import migrations, models
import storages.backends.s3boto3


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='product_image_1',
            field=models.ImageField(storage=storages.backends.s3boto3.S3Boto3Storage(bucket='punam-flutes-prods'), upload_to=''),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='product_image_2',
            field=models.ImageField(blank=True, null=True, storage=storages.backends.s3boto3.S3Boto3Storage(bucket='punam-flutes-prods'), upload_to=''),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='product_image_3',
            field=models.ImageField(blank=True, null=True, storage=storages.backends.s3boto3.S3Boto3Storage(bucket='punam-flutes-prods'), upload_to=''),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='product_image_4',
            field=models.ImageField(blank=True, null=True, storage=storages.backends.s3boto3.S3Boto3Storage(bucket='punam-flutes-prods'), upload_to=''),
        ),
    ]
