# Generated by Django 2.2 on 2021-04-23 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_countrycurrencyrate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countrycurrency',
            name='currency',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
