# Generated by Django 2.2 on 2020-08-12 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_auto_20200729_1634'),
    ]

    operations = [
        migrations.CreateModel(
            name='country_currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
                ('currency', models.CharField(max_length=30)),
            ],
        ),
    ]
