# Generated by Django 2.2 on 2020-08-12 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_auto_20200812_1331'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.DeleteModel(
            name='Currency',
        ),
        migrations.AddField(
            model_name='countrycurrency',
            name='MRP',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='countrycurrency',
            name='country',
            field=models.CharField(blank=True, choices=[['Any', 'Any country'], ['Europe', 'Europe'], ['Asia', 'Asia'], ['Africa', 'Africa']], default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='countrycurrency',
            name='currency',
            field=models.CharField(blank=True, choices=[['USD', 'USD'], ['INR', 'INR'], ['EURO', 'EURO'], ['GBP', 'GBP']], default='', max_length=30, null=True),
        ),
    ]
