# Generated by Django 2.2 on 2021-06-09 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_auto_20210609_0641'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='region_of_origin',
            new_name='country_of_origin',
        ),
    ]
