# Generated by Django 2.2 on 2021-06-11 07:00

from django.db import migrations, models
import storages.backends.s3boto3


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_auto_20210609_0946'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='image_big',
            field=models.ImageField(blank=True, null=True, storage=storages.backends.s3boto3.S3Boto3Storage(bucket='punam-flutes-prods'), upload_to='productImage/%Y%m%d%M%S'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='image_detail',
            field=models.ImageField(blank=True, null=True, storage=storages.backends.s3boto3.S3Boto3Storage(bucket='punam-flutes-prods'), upload_to='productImage/%Y%m%d%M%S'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='image_list',
            field=models.ImageField(blank=True, null=True, storage=storages.backends.s3boto3.S3Boto3Storage(bucket='punam-flutes-prods'), upload_to='productImage/%Y%m%d%M%S'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='image_small',
            field=models.ImageField(blank=True, null=True, storage=storages.backends.s3boto3.S3Boto3Storage(bucket='punam-flutes-prods'), upload_to='productImage/%Y%m%d%M%S'),
        ),
    ]
