# Generated by Django 2.2 on 2020-09-10 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
        ('product', '0011_auto_20200814_1710'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimage',
            old_name='product_image_1',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='product_image_2',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='product_image_3',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='product_image_4',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='product_image_5',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='product_image_6',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(blank=True, null=True, to='category.Category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.ProductImage'),
        ),
    ]
