# Generated by Django 2.2 on 2021-02-25 18:35

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('state', models.CharField(max_length=1024)),
                ('method', models.CharField(choices=[('percent', 'Percent'), ('fixed_amount', 'Fixed Amout')], default='percent', max_length=20)),
                ('value', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.Category')),
            ],
        ),
    ]
