# Generated by Django 2.2 on 2020-05-29 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax_rules', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxrule',
            name='state',
            field=models.CharField(max_length=1024),
        ),
    ]
