country = [
    ['Any', 'Any country'],
    ['Europe', 'Europe'],
    ['Asia', 'Asia'],
    ['Africa', 'Africa'],
    ['NAmerica', 'North America'],
    ['SAmerica', 'South America'],
    ['A_Pacific', 'Asia/Pacific Region'],
    ['Australia', 'Australia'],
    ['Austria', 'Austria'],
    ['Brazil', 'Brazil'],
    ['Canada', 'Canada'],
    ['Chile', 'Chile'],
    ['China', 'China'],
    ['Egypt', 'Egypt'],
    ['France', 'France'],
    ['Georgia', 'Georgia'],
    ['Germany', 'Germany'],
    ['Ghana', 'Ghana'],
    ['Greece', 'Greece'],
    ['India', 'India'],
    ['Indonesia', 'Indonesia'],
    ['Iran', 'Iran'],
    ['Iraq', 'Iraq'],
    ['Ireland', 'Ireland'],
    ['Israel', 'Israel'],
    ['Italy', 'Italy'],
    ['Jamaica', 'Jamaica'],
    ['Japan', 'Japan'],
    ['Kuwait', 'Kuwait'],
    ['Malaysia', 'Malaysia'],
    ['Maldives', 'Maldives'],
    ['Mexico', 'Mexico'],
    ['Nepal', 'Nepal'],
    ['Netherlands', 'Netherlands'],
    ['New_Zealand', 'New Zealand'],
    ['Nigeria', 'Nigeria'],
    ['Oman', 'Oman'],
    ['Pakistan', 'Pakistan'],
    ['Paraguay', 'Paraguay'],
    ['Peru', 'Peru'],
    ['Philippines', 'Philippines'],
    ['Poland', 'Poland'],
    ['Portugal', 'Portugal'],
    ['Romania', 'Romania'],
    ['Russia', 'Russia'],
    ['Saudi_Arabia', 'Saudi Arabia'],
    ['Singapore', 'Singapore'],
    ['South_africa', 'South Africa'],
    ['Spain', 'Spain'],
    ['Sri Lanka', 'Sri Lanka'],
    ['Switzerland', 'Switzerland'],
    ['UAE', 'United Arab Emirates'],
    ['USA', 'United States of America'],
    ['UK', 'United Kingdom']

]
currency = [
    ['USD', 'USD'],
    ['INR', 'INR'],
    ['EURO', 'EURO'],
    ['GBP', 'GBP'],
    ['YEN', 'YEN'],
    ['CAD', 'CAD'],
    ['Hong_kong_dollar', 'Hong Kong Dollar'],
    ['Rubel', 'Rubel'],
    ['AUD', 'AUD'],
    ['CNY', 'CNY'],
    ['Emirates_dhiram', 'Emirates Dirham'],
    ['Bangladeshi_taka', 'Bangladeshi Taka'],
    ['Pakistani_rupee', 'Pakistani Rupee']


]
