IndianStates = [
    ['Andhra Pradesh', 'Andhra Pradesh'],
    ['Arunachal Pradesh', 'Arunachal Pradesh'],
    ['Assam', 'Assam'],
    ['Bihar', 'Bihar'],
    ['Chhattisgarh', 'Chhattisgarh'],
    ['Goa', 'Goa'],
    ['Gujarat', 'Gujarat'],
    ['Haryana', 'Haryana'],
    ['Himachal Pradesh', 'Himachal Pradesh'],
    ['Jharkhand', 'Jharkhand'],
    ['Karnataka', 'Karnataka'],
    ['Kerala', 'Kerala'],
    ['Madhya Pradesh', 'Madhya Pradesh'],
    ['Maharashtra', 'Maharashtra'],
    ['Manipur', 'Manipur'],
    ['Meghalaya', 'Meghalaya'],
    ['Mizoram', 'Mizoram'],
    ['Nagaland', 'Nagaland'],
    ['Odisha', 'Odisha'],
    ['Punjab', 'Punjab'],
    ['Rajasthan', 'Rajasthan'],
    ['Sikkim', 'Sikkim'],
    ['Tamil Nadu', 'Tamil Nadu'],
    ['Telangana', 'Telangana'],
    ['Tripura', 'Tripura'],
    ['Uttar Pradesh', 'Uttar Pradesh'],
    ['Uttarakhand', 'Uttarakhand'],
    ['West Bengal', 'West Bengal']
]
IndianUnionTerritories = [
    ['Andaman and Nicobar Islands', 'Andaman and Nicobar Islands'],
    ['Chandigarh', 'Chandigarh'],
    ['Dadra & Nagar Haveli and Daman & Diu', 'Dadra & Nagar Haveli and Daman & Diu'],
    ['Delhi', 'Delhi'],
    ['Jammu and Kashmir', 'Jammu and Kashmir'],
    ['Lakshadweep', 'Lakshadweep'],
    ['Puducherry', 'Puducherry'],
    ['Ladakh', 'Ladakh']
]
