# Generated by Django 2.2 on 2021-04-16 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_auto_20210316_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='publish',
            field=models.BooleanField(default=True),
        ),
    ]
