# Generated by Django 2.2 on 2021-04-21 15:12

from django.db import migrations, models
import django.utils.timezone
import storages.backends.s3boto3


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_category_publish'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='alt',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, storage=storages.backends.s3boto3.S3Boto3Storage(bucket='punam-flutes-prods'), upload_to='category//%Y%m%d%M%S'),
            preserve_default=False,
        ),
    ]
