# Generated by Django 2.2 on 2020-05-29 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=200)),
                ('menu_item_name', models.CharField(max_length=200)),
                ('sequence', models.IntegerField()),
                ('description', models.TextField()),
                ('blog_type', models.CharField(choices=[('card', 'card'), ('carousal', 'carousal'), ('banner', 'banner')], default='card', max_length=10)),
                ('publish', models.BooleanField(default=False)),
                ('blog_category', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='category.Category')),
            ],
        ),
    ]
