# Generated by Django 2.2 on 2021-05-27 17:47

from django.db import migrations, models
import storages.backends.s3boto3


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_at', models.DateTimeField(auto_now=True, null=True)),
                ('image', models.ImageField(storage=storages.backends.s3boto3.S3Boto3Storage(bucket='punam-flutes-prods'), upload_to='testinomial/%Y%m%d%M%S')),
                ('alt', models.CharField(blank=True, max_length=1024, null=True)),
                ('name', models.CharField(blank=True, max_length=2048, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('publish', models.BooleanField(blank=True, default=True, null=True)),
                ('order', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ('order',),
            },
        ),
    ]
