# Generated by Django 2.2 on 2021-03-16 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'ordering': ('default',), 'verbose_name_plural': 'addresses'},
        ),
        migrations.AddField(
            model_name='address',
            name='address_type',
            field=models.CharField(blank=True, choices=[['billing', 'billing'], ['shipping', 'shipping']], default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='default',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
