# Generated by Django 2.2 on 2021-03-16 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_at', models.DateTimeField(auto_now=True, null=True)),
                ('country', models.CharField(blank=True, choices=[['Any', 'Any country'], ['Europe', 'Europe'], ['Asia', 'Asia'], ['Africa', 'Africa'], ['NAmerica', 'North America'], ['SAmerica', 'South America'], ['A_Pacific', 'Asia/Pacific Region'], ['Australia', 'Australia'], ['Austria', 'Austria'], ['Brazil', 'Brazil'], ['Canada', 'Canada'], ['Chile', 'Chile'], ['China', 'China'], ['Egypt', 'Egypt'], ['France', 'France'], ['Georgia', 'Georgia'], ['Germany', 'Germany'], ['Ghana', 'Ghana'], ['Greece', 'Greece'], ['India', 'India'], ['Indonesia', 'Indonesia'], ['Iran', 'Iran'], ['Iraq', 'Iraq'], ['Ireland', 'Ireland'], ['Israel', 'Israel'], ['Italy', 'Italy'], ['Jamaica', 'Jamaica'], ['Japan', 'Japan'], ['Kuwait', 'Kuwait'], ['Malaysia', 'Malaysia'], ['Maldives', 'Maldives'], ['Mexico', 'Mexico'], ['Nepal', 'Nepal'], ['Netherlands', 'Netherlands'], ['New_Zealand', 'New Zealand'], ['Nigeria', 'Nigeria'], ['Oman', 'Oman'], ['Pakistan', 'Pakistan'], ['Paraguay', 'Paraguay'], ['Peru', 'Peru'], ['Philippines', 'Philippines'], ['Poland', 'Poland'], ['Portugal', 'Portugal'], ['Romania', 'Romania'], ['Russia', 'Russia'], ['Saudi_Arabia', 'Saudi Arabia'], ['Singapore', 'Singapore'], ['South_africa', 'South Africa'], ['Spain', 'Spain'], ['Sri Lanka', 'Sri Lanka'], ['Switzerland', 'Switzerland'], ['UAE', 'United Arab Emirates'], ['USA', 'United States of America'], ['UK', 'United Kingdom']], default='', max_length=100, null=True)),
                ('method', models.CharField(blank=True, choices=[['razorpay', 'razorpay'], ['paypal', 'paypal'], ['COD', 'COD']], max_length=20, null=True, verbose_name='Payment Method')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='payment',
            name='cod',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(blank=True, choices=[['razorpay', 'razorpay'], ['paypal', 'paypal'], ['COD', 'COD']], max_length=20, null=True),
        ),
    ]
