# Generated by Django 2.2 on 2021-03-16 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_auto_20210316_1151'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('delivered',)},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ('status', 'method')},
        ),
    ]
