# Generated by Django 2.2 on 2021-03-19 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_auto_20210316_1810'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='countrypayment',
            name='method',
        ),
        migrations.AddField(
            model_name='countrypayment',
            name='cod',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='countrypayment',
            name='paypal',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='countrypayment',
            name='razorpay',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
