# Generated by Django 2.2 on 2021-04-09 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_auto_20210319_1100'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('created_at',)},
        ),
        migrations.RemoveField(
            model_name='order',
            name='delivered',
        ),
        migrations.AddField(
            model_name='order',
            name='notes',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[['Pending', 'Pending'], ['Confirmed', 'Confirmed'], ['Paid', 'Paid'], ['Dispatch', 'Dispatch'], ['Shipped', 'Shipped'], ['Delivered', 'Delivered'], ['Cancel', 'Cancel'], ['Refunded', 'Refunded']], max_length=50, null=True),
        ),
    ]
