# Generated by Django 2.2 on 2020-09-15 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_auto_20200912_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='total',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
