# Generated by Django 2.2 on 2020-09-15 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
        ('customer', '0001_initial'),
        ('cart', '0006_checkout_total'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Checkout',
            new_name='Order',
        ),
    ]
