# Generated by Django 2.2 on 2021-04-17 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0002_auto_20210416_1641'),
        ('cart', '0006_auto_20210412_0849'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='coupon.Coupon'),
        ),
    ]
