# Generated by Django 2.2 on 2021-04-23 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0009_auto_20210421_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='courier_tracker',
            field=models.TextField(blank=True, null=True),
        ),
    ]
