# Generated by Django 2.2 on 2021-04-26 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0011_auto_20210426_1037'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CountryPayment',
        ),
    ]
