# Generated by Django 2.2 on 2021-05-26 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0012_delete_countrypayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='productquantity',
            name='amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productquantity',
            name='country',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='productquantity',
            name='currency',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='productquantity',
            name='currency_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
