# Generated by Django 2.2 on 2021-04-26 10:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ipn', '0008_auto_20181128_1032'),
        ('coupon', '0002_auto_20210416_1641'),
        ('address', '0003_auto_20210419_1822'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cart', '0011_auto_20210426_1037'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_at', models.DateTimeField(auto_now=True, null=True)),
                ('total', models.FloatField(blank=True, null=True)),
                ('customization_request', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(blank=True, choices=[['Pending', 'Pending'], ['Confirmed', 'Confirmed'], ['Paid', 'Paid'], ['Dispatch', 'Dispatch'], ['Shipped', 'Shipped'], ['Delivered', 'Delivered'], ['Canceled', 'Canceled'], ['Refunded', 'Refunded']], max_length=50, null=True)),
                ('courier_tracker', models.TextField(blank=True, null=True)),
                ('billing_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_address', to='address.Address')),
                ('cart', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cart.Cart')),
                ('coupon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='coupon.Coupon')),
                ('shipping_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipping_address', to='address.Address')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_at', models.DateTimeField(auto_now=True, null=True)),
                ('method', models.CharField(blank=True, choices=[['razorpay', 'razorpay'], ['paypal', 'paypal'], ['COD', 'COD']], max_length=20, null=True)),
                ('razorpay', models.CharField(blank=True, max_length=25, null=True)),
                ('cod', models.CharField(blank=True, max_length=25, null=True)),
                ('status', models.BooleanField(default=False)),
                ('order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.Order')),
                ('paypal', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ipn.PayPalIPN')),
            ],
            options={
                'ordering': ('status', 'method'),
            },
        ),
    ]
