# Generated by Django 2.2 on 2021-05-25 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_courrierorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_placed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
