# Generated by Django 2.2 on 2021-06-01 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_order_order_placed'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='method_name',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
