# Generated by Django 2.2 on 2021-06-03 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_auto_20210601_0654'),
    ]

    operations = [
        migrations.AddField(
            model_name='courrierorder',
            name='courrier_booked_status',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
